"""SocksIP version diagnostics: supported methods and unknown VER6/VER7.

Only synthetic profiles generated by the repository are tested.
Unknown formats are never promoted to successful decodes.
"""
from __future__ import annotations

import base64
import unittest

from Crypto.Cipher import AES
from Crypto.Util.Padding import pad, unpad

from decoders.Python.sockip import SIP_AES_KEY
from scripts.inspect_socksip_versions import inspect_sip
from tests.golden.hc_sip_new_variants import sip_ver8_file, sip_file


def wrap_unknown_version(version: int, content: bytes) -> bytes:
    payload = ("VER" + str(version)).encode("ascii") + content
    ciphertext = AES.new(SIP_AES_KEY, AES.MODE_ECB).encrypt(pad(payload, 16))
    return base64.b64encode(ciphertext)


class SocksIPVersionInspectionTests(unittest.TestCase):
    def test_legacy_preserves_existing_decoder(self):
        report = inspect_sip(sip_file())
        self.assertEqual(report["version"], "legacy-java")
        self.assertTrue(report["parse_supported"])
        self.assertNotIn("server", report)

    def test_ver8_authenticates_with_supplied_literal_key(self):
        report = inspect_sip(sip_ver8_file())
        self.assertEqual(report["version"], "VER8")
        self.assertEqual(report["inner_cipher"], "AES-256-GCM")
        self.assertEqual(report["authentication"], "verified")
        self.assertTrue(report["parse_supported"])
        self.assertNotIn("example.org", str(report))

    def test_ver7_is_recognized_not_assumed_gcm(self):
        report = inspect_sip(wrap_unknown_version(7, b"aabbccddee00ff"))
        self.assertEqual(report["version"], "VER7")
        self.assertTrue(report["inner"]["hex_text_candidate"])
        self.assertEqual(report["inner_cipher"], "unknown")
        self.assertFalse(report["parse_supported"])

    def test_ver6_is_recognized_not_assumed_gcm(self):
        report = inspect_sip(wrap_unknown_version(6, b"some-other-binary-\x00\xff"))
        self.assertEqual(report["version"], "VER6")
        self.assertEqual(report["inner_cipher"], "unknown")
        self.assertFalse(report["parse_supported"])

    def test_ver8_bad_gcm_tag_reports_failure_not_plaintext(self):
        original = base64.b64decode(sip_ver8_file())
        clear = bytearray(unpad(AES.new(SIP_AES_KEY, AES.MODE_ECB).decrypt(original), 16))
        clear[-1] ^= 0x01
        broken = base64.b64encode(AES.new(SIP_AES_KEY, AES.MODE_ECB).encrypt(pad(clear, 16)))
        report = inspect_sip(broken)
        self.assertEqual(report["version"], "VER8")
        self.assertEqual(report["authentication"], "failed")
        self.assertFalse(report["parse_supported"])
        self.assertNotIn("server", str(report))

    def test_fails_on_unreadable_outer_container(self):
        with self.assertRaises(ValueError):
            inspect_sip(b"invalid!~base64")


if __name__ == "__main__":
    unittest.main()
